name: SignCommand
main: iTzFreeHD\Ssigncommand\Main
api:
- 3.0.0
version: 3.0
commands:
  sign:
    description: SignCommand info
    default: op
permissions:
  player.sign:
    default: true
  vip.sign:
    default: op
  admin.sign:
    default: op
  console.sign:
    default: op
